// Code generated by goyacc - DO NOT EDIT.

package oralce_sql_parser

import __yyfmt__ "fmt"

import (
	"github.com/sjjian/oralce_sql_parser/ast"
	"github.com/sjjian/oralce_sql_parser/ast/element"
)

type yySymType struct {
	yys      int
	nothing  struct{}
	i        int
	str      string
	node     ast.Node
	anything interface{}
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault            = 57397
	yyEofCode            = 57344
	_add                 = 57350
	_alter               = 57348
	_bfile               = 57377
	_binaryDouble        = 57359
	_binaryFloat         = 57358
	_blob                = 57374
	_byte                = 57352
	_char                = 57351
	_character           = 57380
	_clob                = 57375
	_date                = 57362
	_day                 = 57372
	_dec                 = 57386
	_decimal             = 57385
	_double              = 57390
	_doubleQuoteStr      = 57395
	_float               = 57357
	_from                = 57347
	_int                 = 57388
	_intNumber           = 57393
	_interger            = 57387
	_interval            = 57368
	_local               = 57365
	_long                = 57360
	_mouth               = 57371
	_national            = 57383
	_nchar               = 57354
	_nclob               = 57376
	_nonquotedIdentifier = 57396
	_number              = 57356
	_numeric             = 57384
	_nvarchar2           = 57355
	_precision           = 57391
	_raw                 = 57361
	_real                = 57392
	_rowid               = 57378
	_second              = 57373
	_select              = 57346
	_singleQuoteStr      = 57394
	_smallInt            = 57389
	_table               = 57349
	_time                = 57366
	_timestamp           = 57363
	_to                  = 57370
	_urowid              = 57379
	_varchar             = 57382
	_varchar2            = 57353
	_varying             = 57381
	_with                = 57364
	_year                = 57369
	_zone                = 57367
	yyErrCode            = 57345

	yyMaxDepth = 200
	yyTabOfs   = -103
)

var (
	yyPrec = map[int]int{}

	yyXLAT = map[int]int{
		41:    0,  // ')' (113x)
		44:    1,  // ',' (81x)
		57393: 2,  // _intNumber (29x)
		40:    3,  // '(' (26x)
		57344: 4,  // $end (21x)
		57350: 5,  // _add (16x)
		46:    6,  // '.' (8x)
		57351: 7,  // _char (7x)
		42:    8,  // '*' (5x)
		57380: 9,  // _character (5x)
		57361: 10, // _raw (5x)
		57381: 11, // _varying (5x)
		57422: 12, // NumberOrAsterisk (5x)
		57377: 13, // _bfile (4x)
		57359: 14, // _binaryDouble (4x)
		57358: 15, // _binaryFloat (4x)
		57374: 16, // _blob (4x)
		57375: 17, // _clob (4x)
		57362: 18, // _date (4x)
		57386: 19, // _dec (4x)
		57385: 20, // _decimal (4x)
		57390: 21, // _double (4x)
		57395: 22, // _doubleQuoteStr (4x)
		57357: 23, // _float (4x)
		57388: 24, // _int (4x)
		57387: 25, // _interger (4x)
		57368: 26, // _interval (4x)
		57360: 27, // _long (4x)
		57383: 28, // _national (4x)
		57354: 29, // _nchar (4x)
		57376: 30, // _nclob (4x)
		57396: 31, // _nonquotedIdentifier (4x)
		57356: 32, // _number (4x)
		57384: 33, // _numeric (4x)
		57355: 34, // _nvarchar2 (4x)
		57392: 35, // _real (4x)
		57378: 36, // _rowid (4x)
		57389: 37, // _smallInt (4x)
		57363: 38, // _timestamp (4x)
		57370: 39, // _to (4x)
		57379: 40, // _urowid (4x)
		57382: 41, // _varchar (4x)
		57353: 42, // _varchar2 (4x)
		57414: 43, // Identifier (4x)
		57352: 44, // _byte (2x)
		57371: 45, // _mouth (2x)
		57373: 46, // _second (2x)
		57366: 47, // _time (2x)
		57367: 48, // _zone (2x)
		57398: 49, // AddColumnClause (2x)
		57401: 50, // ChangeColumnClause (2x)
		57406: 51, // ColumnDefinition (2x)
		57408: 52, // ColumnName (2x)
		57413: 53, // DropColumnClause (2x)
		57420: 54, // ModidyColumnClause (2x)
		57425: 55, // RealColumnDefinition (2x)
		57348: 56, // _alter (1x)
		57372: 57, // _day (1x)
		57365: 58, // _local (1x)
		57391: 59, // _precision (1x)
		57349: 60, // _table (1x)
		57364: 61, // _with (1x)
		57369: 62, // _year (1x)
		57399: 63, // AlterTableStmt (1x)
		57400: 64, // AnsiSupportDataTypes (1x)
		57402: 65, // ChangeColumnClauseList (1x)
		57403: 66, // CharacterDataTypes (1x)
		57404: 67, // CollateClause (1x)
		57405: 68, // ColumnClauses (1x)
		57407: 69, // ColumnDefinitionList (1x)
		57409: 70, // ColumnProperties (1x)
		57410: 71, // Datatype (1x)
		57411: 72, // DatetimeDataTypes (1x)
		57412: 73, // DefaultProperties (1x)
		57415: 74, // InvisibleProperty (1x)
		57416: 75, // LargeObjectDataTypes (1x)
		57417: 76, // LongAndRawDataTypes (1x)
		57418: 77, // MemoptimizeReadClause (1x)
		57419: 78, // MemoptimizeWriteClause (1x)
		57421: 79, // NumberDataTypes (1x)
		57423: 80, // OralceBuiltInDataTypes (1x)
		57424: 81, // OutOfLinePartStorageList (1x)
		57426: 82, // RenameColumnClause (1x)
		57427: 83, // RowIdDataTypes (1x)
		57428: 84, // SortProperty (1x)
		57429: 85, // Start (1x)
		57430: 86, // Statement (1x)
		57431: 87, // TableName (1x)
		57397: 88, // $default (0x)
		57347: 89, // _from (0x)
		57346: 90, // _select (0x)
		57394: 91, // _singleQuoteStr (0x)
		57345: 92, // error (0x)
	}

	yySymNames = []string{
		"')'",
		"','",
		"_intNumber",
		"'('",
		"$end",
		"_add",
		"'.'",
		"_char",
		"'*'",
		"_character",
		"_raw",
		"_varying",
		"NumberOrAsterisk",
		"_bfile",
		"_binaryDouble",
		"_binaryFloat",
		"_blob",
		"_clob",
		"_date",
		"_dec",
		"_decimal",
		"_double",
		"_doubleQuoteStr",
		"_float",
		"_int",
		"_interger",
		"_interval",
		"_long",
		"_national",
		"_nchar",
		"_nclob",
		"_nonquotedIdentifier",
		"_number",
		"_numeric",
		"_nvarchar2",
		"_real",
		"_rowid",
		"_smallInt",
		"_timestamp",
		"_to",
		"_urowid",
		"_varchar",
		"_varchar2",
		"Identifier",
		"_byte",
		"_mouth",
		"_second",
		"_time",
		"_zone",
		"AddColumnClause",
		"ChangeColumnClause",
		"ColumnDefinition",
		"ColumnName",
		"DropColumnClause",
		"ModidyColumnClause",
		"RealColumnDefinition",
		"_alter",
		"_day",
		"_local",
		"_precision",
		"_table",
		"_with",
		"_year",
		"AlterTableStmt",
		"AnsiSupportDataTypes",
		"ChangeColumnClauseList",
		"CharacterDataTypes",
		"CollateClause",
		"ColumnClauses",
		"ColumnDefinitionList",
		"ColumnProperties",
		"Datatype",
		"DatetimeDataTypes",
		"DefaultProperties",
		"InvisibleProperty",
		"LargeObjectDataTypes",
		"LongAndRawDataTypes",
		"MemoptimizeReadClause",
		"MemoptimizeWriteClause",
		"NumberDataTypes",
		"OralceBuiltInDataTypes",
		"OutOfLinePartStorageList",
		"RenameColumnClause",
		"RowIdDataTypes",
		"SortProperty",
		"Start",
		"Statement",
		"TableName",
		"$default",
		"_from",
		"_select",
		"_singleQuoteStr",
		"error",
	}

	yyTokenLiteralStrings = map[int]string{
		57393: "int number",
		57395: "double quotes string",
		57396: "nonquoted identifier",
		57394: "single quotes string",
	}

	yyReductions = map[int]struct{ xsym, components int }{
		0:   {0, 1},
		1:   {85, 1},
		2:   {86, 1},
		3:   {63, 6},
		4:   {87, 1},
		5:   {87, 3},
		6:   {43, 1},
		7:   {43, 1},
		8:   {77, 0},
		9:   {78, 0},
		10:  {68, 1},
		11:  {68, 1},
		12:  {65, 1},
		13:  {65, 2},
		14:  {50, 1},
		15:  {50, 1},
		16:  {50, 1},
		17:  {49, 6},
		18:  {70, 0},
		19:  {81, 0},
		20:  {54, 0},
		21:  {53, 0},
		22:  {82, 0},
		23:  {69, 1},
		24:  {69, 3},
		25:  {51, 1},
		26:  {55, 6},
		27:  {52, 1},
		28:  {67, 0},
		29:  {84, 0},
		30:  {74, 0},
		31:  {73, 0},
		32:  {71, 1},
		33:  {71, 1},
		34:  {12, 1},
		35:  {12, 1},
		36:  {80, 1},
		37:  {80, 1},
		38:  {80, 1},
		39:  {80, 1},
		40:  {80, 1},
		41:  {80, 1},
		42:  {66, 1},
		43:  {66, 4},
		44:  {66, 5},
		45:  {66, 5},
		46:  {66, 4},
		47:  {66, 5},
		48:  {66, 5},
		49:  {66, 1},
		50:  {66, 4},
		51:  {66, 4},
		52:  {79, 1},
		53:  {79, 4},
		54:  {79, 6},
		55:  {79, 1},
		56:  {79, 4},
		57:  {79, 1},
		58:  {79, 1},
		59:  {76, 1},
		60:  {76, 2},
		61:  {76, 4},
		62:  {72, 1},
		63:  {72, 1},
		64:  {72, 4},
		65:  {72, 7},
		66:  {72, 8},
		67:  {72, 4},
		68:  {72, 7},
		69:  {72, 4},
		70:  {72, 7},
		71:  {72, 10},
		72:  {72, 7},
		73:  {75, 1},
		74:  {75, 1},
		75:  {75, 1},
		76:  {75, 1},
		77:  {83, 1},
		78:  {83, 1},
		79:  {83, 4},
		80:  {64, 4},
		81:  {64, 5},
		82:  {64, 5},
		83:  {64, 5},
		84:  {64, 4},
		85:  {64, 5},
		86:  {64, 6},
		87:  {64, 5},
		88:  {64, 6},
		89:  {64, 1},
		90:  {64, 4},
		91:  {64, 6},
		92:  {64, 1},
		93:  {64, 4},
		94:  {64, 6},
		95:  {64, 1},
		96:  {64, 4},
		97:  {64, 6},
		98:  {64, 1},
		99:  {64, 1},
		100: {64, 1},
		101: {64, 2},
		102: {64, 1},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [199][]uint16{
		// 0
		{56: 107, 63: 106, 85: 104, 105},
		{4: 103},
		{4: 102},
		{4: 101},
		{60: 108},
		// 5
		{22: 112, 31: 111, 43: 110, 87: 109},
		{4: 95, 95, 77: 115},
		{4: 99, 99, 113},
		{4: 97, 97, 97, 97, 9: 97, 97, 13: 97, 97, 97, 97, 97, 97, 97, 97, 97, 23: 97, 97, 97, 97, 97, 97, 97, 97, 32: 97, 97, 97, 97, 97, 97, 97, 40: 97, 97, 97},
		{4: 96, 96, 96, 96, 9: 96, 96, 13: 96, 96, 96, 96, 96, 96, 96, 96, 96, 23: 96, 96, 96, 96, 96, 96, 96, 96, 32: 96, 96, 96, 96, 96, 96, 96, 40: 96, 96, 96},
		// 10
		{22: 112, 31: 111, 43: 114},
		{4: 98, 98},
		{4: 94, 94, 78: 116},
		{4: 83, 124, 49: 121, 120, 53: 123, 122, 65: 118, 68: 117, 82: 119},
		{4: 100},
		// 15
		{4: 93, 124, 49: 121, 301, 53: 123, 122},
		{4: 92},
		{4: 91, 91},
		{4: 89, 89},
		{4: 88, 88},
		// 20
		{4: 87, 87},
		{3: 125},
		{22: 112, 31: 111, 43: 130, 51: 127, 129, 55: 128, 69: 126},
		{296, 297},
		{80, 80},
		// 25
		{78, 78},
		{7: 140, 9: 159, 149, 13: 156, 147, 146, 153, 154, 150, 164, 163, 168, 23: 145, 166, 165, 152, 148, 161, 142, 155, 32: 144, 162, 143, 169, 157, 167, 151, 40: 158, 160, 141, 64: 133, 66: 134, 71: 131, 137, 75: 138, 136, 79: 135, 132, 83: 139},
		{7: 76, 9: 76, 76, 13: 76, 76, 76, 76, 76, 76, 76, 76, 76, 23: 76, 76, 76, 76, 76, 76, 76, 76, 32: 76, 76, 76, 76, 76, 76, 76, 40: 76, 76, 76},
		{75, 75, 67: 292},
		{71, 71},
		// 30
		{70, 70},
		{67, 67},
		{66, 66},
		{65, 65},
		{64, 64},
		// 35
		{63, 63},
		{62, 62},
		{61, 61, 3: 281, 11: 282},
		{3: 274},
		{54, 54, 3: 267, 11: 268},
		// 40
		{3: 264},
		{51, 51, 3: 258},
		{48, 48, 3: 255},
		{46, 46},
		{45, 45},
		// 45
		{44, 44, 10: 254},
		{3: 251},
		{41, 41},
		{40, 40, 3: 242},
		{57: 221, 62: 220},
		// 50
		{30, 30},
		{29, 29},
		{28, 28},
		{27, 27},
		{26, 26},
		// 55
		{25, 25, 3: 217},
		{3: 210, 11: 211},
		{3: 207},
		{7: 192, 9: 191},
		{14, 14, 3: 185},
		// 60
		{11, 11, 3: 179},
		{8, 8, 3: 171},
		{5, 5},
		{4, 4},
		{3, 3},
		// 65
		{59: 170},
		{1, 1},
		{2, 2},
		{2: 172, 8: 173, 12: 174},
		{69, 69, 6: 69},
		// 70
		{68, 68, 6: 68},
		{175, 6: 176},
		{7, 7},
		{2: 177},
		{178},
		// 75
		{6, 6},
		{2: 172, 8: 173, 12: 180},
		{181, 6: 182},
		{10, 10},
		{2: 183},
		// 80
		{184},
		{9, 9},
		{2: 172, 8: 173, 12: 186},
		{187, 6: 188},
		{13, 13},
		// 85
		{2: 189},
		{190},
		{12, 12},
		{3: 200, 11: 201},
		{3: 193, 11: 194},
		// 90
		{2: 198},
		{3: 195},
		{2: 196},
		{197},
		{15, 15},
		// 95
		{199},
		{16, 16},
		{2: 205},
		{3: 202},
		{2: 203},
		// 100
		{204},
		{17, 17},
		{206},
		{18, 18},
		{2: 208},
		// 105
		{209},
		{19, 19},
		{2: 215},
		{3: 212},
		{2: 213},
		// 110
		{214},
		{22, 22},
		{216},
		{23, 23},
		{2: 218},
		// 115
		{219},
		{24, 24},
		{3: 236, 39: 235},
		{3: 223, 39: 222},
		{46: 231},
		// 120
		{2: 224},
		{225},
		{39: 226},
		{46: 227},
		{33, 33, 3: 228},
		// 125
		{2: 229},
		{230},
		{32, 32},
		{34, 34, 3: 232},
		{2: 233},
		// 130
		{234},
		{31, 31},
		{45: 241},
		{2: 237},
		{238},
		// 135
		{39: 239},
		{45: 240},
		{35, 35},
		{36, 36},
		{2: 243},
		// 140
		{244},
		{39, 39, 61: 245},
		{47: 246, 58: 247},
		{48: 250},
		{47: 248},
		// 145
		{48: 249},
		{37, 37},
		{38, 38},
		{2: 252},
		{253},
		// 150
		{42, 42},
		{43, 43},
		{2: 172, 8: 173, 12: 256},
		{257},
		{47, 47},
		// 155
		{2: 172, 8: 173, 12: 259},
		{260, 261},
		{50, 50},
		{2: 262},
		{263},
		// 160
		{49, 49},
		{2: 265},
		{266},
		{52, 52},
		{2: 272},
		// 165
		{3: 269},
		{2: 270},
		{271},
		{20, 20},
		{273},
		// 170
		{53, 53},
		{2: 275},
		{276, 7: 278, 44: 277},
		{57, 57},
		{280},
		// 175
		{279},
		{55, 55},
		{56, 56},
		{2: 286},
		{3: 283},
		// 180
		{2: 284},
		{285},
		{21, 21},
		{287, 7: 289, 44: 288},
		{60, 60},
		// 185
		{291},
		{290},
		{58, 58},
		{59, 59},
		{74, 74, 84: 293},
		// 190
		{73, 73, 74: 294},
		{72, 72, 73: 295},
		{77, 77},
		{4: 85, 85, 70: 299},
		{22: 112, 31: 111, 43: 130, 51: 298, 129, 55: 128},
		// 195
		{79, 79},
		{4: 84, 84, 81: 300},
		{4: 86, 86},
		{4: 90, 90},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 92

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			yylex.(*yyLexImpl).result = yyS[yypt-0].node
		}
	case 2:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 3:
		{
			yyVAL.node = &ast.AlterTableStmt{
				TableName:     yyS[yypt-3].anything.(*ast.TableName),
				ColumnClauses: yyS[yypt-0].anything.([]ast.ColumnClause),
			}
		}
	case 4:
		{
			yyVAL.anything = &ast.TableName{
				Table: yyS[yypt-0].anything.(*element.Identifier),
			}
		}
	case 5:
		{
			yyVAL.anything = &ast.TableName{
				Schema: yyS[yypt-2].anything.(*element.Identifier),
				Table:  yyS[yypt-0].anything.(*element.Identifier),
			}
		}
	case 6:
		{
			yyVAL.anything = &element.Identifier{
				Typ:   element.IdentifierTypeNonQuoted,
				Value: yyS[yypt-0].str,
			}
		}
	case 7:
		{
			yyVAL.anything = &element.Identifier{
				Typ:   element.IdentifierTypeQuoted,
				Value: yyS[yypt-0].str,
			}
		}
	case 10:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 11:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 12:
		{
			yyVAL.anything = []ast.ColumnClause{yyS[yypt-0].anything.(ast.ColumnClause)}
		}
	case 13:
		{
			yyVAL.anything = append(yyS[yypt-1].anything.([]ast.ColumnClause), yyS[yypt-0].anything.(ast.ColumnClause))
		}
	case 14:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 15:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 16:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 17:
		{
			yyVAL.anything = &ast.AddColumnClause{
				Columns: yyS[yypt-3].anything.([]*ast.ColumnDefine),
			}
		}
	case 20:
		{
			// todo:
		}
	case 21:
		{
			// todo:
		}
	case 22:
		{
			// todo:
		}
	case 23:
		{
			yyVAL.anything = []*ast.ColumnDefine{yyS[yypt-0].anything.(*ast.ColumnDefine)}
		}
	case 24:
		{
			yyVAL.anything = append(yyS[yypt-2].anything.([]*ast.ColumnDefine), yyS[yypt-0].anything.(*ast.ColumnDefine))
		}
	case 25:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 26:
		{
			yyVAL.anything = &ast.ColumnDefine{
				ColumnName: yyS[yypt-5].anything.(*element.Identifier),
				Datatype:   yyS[yypt-4].anything.(element.Datatype),
			}
		}
	case 27:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 32:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 33:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 34:
		{
			yyVAL.anything = &element.NumberOrAsterisk{Number: yyS[yypt-0].i}
		}
	case 35:
		{
			yyVAL.anything = &element.NumberOrAsterisk{IsAsterisk: true}
		}
	case 36:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 37:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 38:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 39:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 40:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 41:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 42:
		{
			d := &element.Char{}
			d.SetDataDefine(element.DataDefineChar)
			yyVAL.anything = d
		}
	case 43:
		{
			size := yyS[yypt-1].i
			d := &element.Char{Size: &size}
			d.SetDataDefine(element.DataDefineChar)
			yyVAL.anything = d
		}
	case 44:
		{
			size := yyS[yypt-2].i
			d := &element.Char{Size: &size, IsByteSize: true}
			d.SetDataDefine(element.DataDefineChar)
			yyVAL.anything = d
		}
	case 45:
		{
			size := yyS[yypt-2].i
			d := &element.Char{Size: &size, IsCharSize: true}
			d.SetDataDefine(element.DataDefineChar)
			d.SetDataDefine(element.DataDefineChar)
			yyVAL.anything = d
		}
	case 46:
		{
			size := yyS[yypt-1].i
			d := &element.Varchar2{}
			d.Size = &size
			d.SetDataDefine(element.DataDefineVarchar2)
			yyVAL.anything = d
		}
	case 47:
		{
			size := yyS[yypt-2].i
			d := &element.Varchar2{}
			d.Size = &size
			d.IsByteSize = true
			d.SetDataDefine(element.DataDefineVarchar2)
			yyVAL.anything = d
		}
	case 48:
		{
			size := yyS[yypt-2].i
			d := &element.Varchar2{}
			d.Size = &size
			d.IsCharSize = true
			d.SetDataDefine(element.DataDefineVarchar2)
			yyVAL.anything = d
		}
	case 49:
		{
			d := &element.NChar{}
			d.SetDataDefine(element.DataDefineNChar)
			yyVAL.anything = d
		}
	case 50:
		{
			size := yyS[yypt-1].i
			d := &element.NChar{Size: &size}
			d.SetDataDefine(element.DataDefineNChar)
			yyVAL.anything = d
		}
	case 51:
		{
			size := yyS[yypt-1].i
			d := &element.NVarchar2{}
			d.Size = &size
			d.SetDataDefine(element.DataDefineNVarChar2)
			yyVAL.anything = d
		}
	case 52:
		{
			d := &element.Number{}
			d.SetDataDefine(element.DataDefineNumber)
			yyVAL.anything = d
		}
	case 53:
		{
			precision := yyS[yypt-1].anything.(*element.NumberOrAsterisk)
			d := &element.Number{Precision: precision}
			d.SetDataDefine(element.DataDefineNumber)
			yyVAL.anything = d
		}
	case 54:
		{
			precision := yyS[yypt-3].anything.(*element.NumberOrAsterisk)
			scale := yyS[yypt-1].i
			d := &element.Number{Precision: precision, Scale: &scale}
			d.SetDataDefine(element.DataDefineNumber)
			yyVAL.anything = d
		}
	case 55:
		{
			d := &element.Float{}
			d.SetDataDefine(element.DataDefineFloat)
			yyVAL.anything = d
		}
	case 56:
		{
			precision := yyS[yypt-1].anything.(*element.NumberOrAsterisk)
			d := &element.Float{Precision: precision}
			d.SetDataDefine(element.DataDefineFloat)
			yyVAL.anything = d
		}
	case 57:
		{
			d := &element.BinaryFloat{}
			d.SetDataDefine(element.DataDefineBinaryFloat)
			yyVAL.anything = d
		}
	case 58:
		{
			d := &element.BinaryDouble{}
			d.SetDataDefine(element.DataDefineBinaryDouble)
			yyVAL.anything = d
		}
	case 59:
		{
			d := &element.Long{}
			d.SetDataDefine(element.DataDefineLong)
			yyVAL.anything = d
		}
	case 60:
		{
			d := &element.LongRaw{}
			d.SetDataDefine(element.DataDefineLongRaw)
			yyVAL.anything = d
		}
	case 61:
		{
			size := yyS[yypt-1].i
			d := &element.Raw{Size: &size}
			d.SetDataDefine(element.DataDefineRaw)
			yyVAL.anything = d
		}
	case 62:
		{
			d := &element.Date{}
			d.SetDataDefine(element.DataDefineDate)
			yyVAL.anything = d
		}
	case 63:
		{
			d := &element.Timestamp{}
			d.SetDataDefine(element.DataDefineTimestamp)
			yyVAL.anything = d
		}
	case 64:
		{
			precision := yyS[yypt-1].i
			d := &element.Timestamp{FractionalSecondsPrecision: &precision}
			d.SetDataDefine(element.DataDefineTimestamp)
			yyVAL.anything = d
		}
	case 65:
		{
			precision := yyS[yypt-4].i
			d := &element.Timestamp{FractionalSecondsPrecision: &precision, WithTimeZone: true}
			d.SetDataDefine(element.DataDefineTimestamp)
			yyVAL.anything = d
		}
	case 66:
		{
			precision := yyS[yypt-5].i
			d := &element.Timestamp{FractionalSecondsPrecision: &precision, WithLocalTimeZone: true}
			d.SetDataDefine(element.DataDefineTimestamp)
			yyVAL.anything = d
		}
	case 67:
		{
			d := &element.IntervalYear{}
			d.SetDataDefine(element.DataDefineIntervalYear)
			yyVAL.anything = d
		}
	case 68:
		{
			precision := yyS[yypt-3].i
			d := &element.IntervalYear{Precision: &precision}
			d.SetDataDefine(element.DataDefineIntervalYear)
			yyVAL.anything = d
		}
	case 69:
		{
			d := &element.IntervalDay{}
			d.SetDataDefine(element.DataDefineIntervalDay)
			yyVAL.anything = d
		}
	case 70:
		{
			precision := yyS[yypt-3].i
			d := &element.IntervalDay{Precision: &precision}
			d.SetDataDefine(element.DataDefineIntervalDay)
			yyVAL.anything = d
		}
	case 71:
		{
			precision := yyS[yypt-6].i
			sPrecision := yyS[yypt-1].i
			d := &element.IntervalDay{Precision: &precision, FractionalSecondsPrecision: &sPrecision}
			d.SetDataDefine(element.DataDefineIntervalDay)
			yyVAL.anything = d
		}
	case 72:
		{
			sPrecision := yyS[yypt-1].i
			d := &element.IntervalDay{FractionalSecondsPrecision: &sPrecision}
			d.SetDataDefine(element.DataDefineIntervalDay)
			yyVAL.anything = d
		}
	case 73:
		{
			d := &element.Blob{}
			d.SetDataDefine(element.DataDefineBlob)
			yyVAL.anything = d
		}
	case 74:
		{
			d := &element.Clob{}
			d.SetDataDefine(element.DataDefineClob)
			yyVAL.anything = d
		}
	case 75:
		{
			d := &element.NClob{}
			d.SetDataDefine(element.DataDefineNClob)
			yyVAL.anything = d
		}
	case 76:
		{
			d := &element.BFile{}
			d.SetDataDefine(element.DataDefineBFile)
			yyVAL.anything = d
		}
	case 77:
		{
			d := &element.RowId{}
			d.SetDataDefine(element.DataDefineRowId)
			yyVAL.anything = d
		}
	case 78:
		{
			d := &element.URowId{}
			d.SetDataDefine(element.DataDefineURowId)
			yyVAL.anything = d
		}
	case 79:
		{
			size := yyS[yypt-1].i
			d := &element.URowId{Size: &size}
			d.SetDataDefine(element.DataDefineURowId)
			yyVAL.anything = d
		}
	case 80:
		{
			d := &element.Char{}
			d.SetDataDefine(element.DataDefineCharacter)
			yyVAL.anything = d
		}
	case 81:
		{
			size := yyS[yypt-1].i
			d := &element.Varchar2{}
			d.Size = &size
			d.SetDataDefine(element.DataDefineCharacterVarying)
			yyVAL.anything = d
		}
	case 82:
		{
			size := yyS[yypt-1].i
			d := &element.Varchar2{}
			d.Size = &size
			d.SetDataDefine(element.DataDefineCharVarying)
			yyVAL.anything = d
		}
	case 83:
		{
			size := yyS[yypt-1].i
			d := &element.NVarchar2{}
			d.Size = &size
			d.SetDataDefine(element.DataDefineNCharVarying)
			yyVAL.anything = d
		}
	case 84:
		{
			size := yyS[yypt-1].i
			d := &element.Varchar2{}
			d.Size = &size
			d.SetDataDefine(element.DataDefineVarchar)
			yyVAL.anything = d
		}
	case 85:
		{
			size := yyS[yypt-1].i
			d := &element.NChar{Size: &size}
			d.SetDataDefine(element.DataDefineNationalCharacter)
			yyVAL.anything = d
		}
	case 86:
		{
			size := yyS[yypt-1].i
			d := &element.NVarchar2{}
			d.Size = &size
			d.SetDataDefine(element.DataDefineNationalCharacterVarying)
			yyVAL.anything = d
		}
	case 87:
		{
			size := yyS[yypt-1].i
			d := &element.NChar{Size: &size}
			d.SetDataDefine(element.DataDefineNationalChar)
			yyVAL.anything = d
		}
	case 88:
		{
			size := yyS[yypt-1].i
			d := &element.NVarchar2{}
			d.Size = &size
			d.SetDataDefine(element.DataDefineNationalCharVarying)
			yyVAL.anything = d
		}
	case 89:
		{
			d := &element.Number{}
			d.SetDataDefine(element.DataDefineNumeric)
			yyVAL.anything = d
		}
	case 90:
		{
			precision := yyS[yypt-1].anything.(*element.NumberOrAsterisk)
			d := &element.Number{Precision: precision}
			d.SetDataDefine(element.DataDefineNumeric)
			yyVAL.anything = d
		}
	case 91:
		{
			precision := yyS[yypt-3].anything.(*element.NumberOrAsterisk)
			scale := yyS[yypt-1].i
			d := &element.Number{Precision: precision, Scale: &scale}
			d.SetDataDefine(element.DataDefineNumeric)
			yyVAL.anything = d
		}
	case 92:
		{
			d := &element.Number{}
			d.SetDataDefine(element.DataDefineDecimal)
			yyVAL.anything = d
		}
	case 93:
		{
			precision := yyS[yypt-1].anything.(*element.NumberOrAsterisk)
			d := &element.Number{Precision: precision}
			d.SetDataDefine(element.DataDefineDecimal)
			yyVAL.anything = d
		}
	case 94:
		{
			precision := yyS[yypt-3].anything.(*element.NumberOrAsterisk)
			scale := yyS[yypt-1].i
			d := &element.Number{Precision: precision, Scale: &scale}
			d.SetDataDefine(element.DataDefineDecimal)
			yyVAL.anything = d
		}
	case 95:
		{
			d := &element.Number{}
			d.SetDataDefine(element.DataDefineDec)
			yyVAL.anything = d
		}
	case 96:
		{
			precision := yyS[yypt-1].anything.(*element.NumberOrAsterisk)
			d := &element.Number{Precision: precision}
			d.SetDataDefine(element.DataDefineDec)
			yyVAL.anything = d
		}
	case 97:
		{
			precision := yyS[yypt-3].anything.(*element.NumberOrAsterisk)
			scale := yyS[yypt-1].i
			d := &element.Number{Precision: precision, Scale: &scale}
			d.SetDataDefine(element.DataDefineDec)
			yyVAL.anything = d
		}
	case 98:
		{
			precision := &element.NumberOrAsterisk{Number: 38}
			d := &element.Number{Precision: precision}
			d.SetDataDefine(element.DataDefineInteger)
			yyVAL.anything = d
		}
	case 99:
		{
			precision := &element.NumberOrAsterisk{Number: 38}
			d := &element.Number{Precision: precision}
			d.SetDataDefine(element.DataDefineInt)
			yyVAL.anything = d
		}
	case 100:
		{
			precision := &element.NumberOrAsterisk{Number: 38}
			d := &element.Number{Precision: precision}
			d.SetDataDefine(element.DataDefineSmallInt)
			yyVAL.anything = d
		}
	case 101:
		{
			precision := &element.NumberOrAsterisk{Number: 126}
			d := &element.Float{Precision: precision}
			d.SetDataDefine(element.DataDefineDoublePrecision)
			yyVAL.anything = d
		}
	case 102:
		{
			precision := &element.NumberOrAsterisk{Number: 63}
			d := &element.Float{Precision: precision}
			d.SetDataDefine(element.DataDefineReal)
			yyVAL.anything = d
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
