// Code generated by goyacc - DO NOT EDIT.

package oralce_sql_parser

import __yyfmt__ "fmt"

import (
	"github.com/sjjian/oralce_sql_parser/ast"
	"github.com/sjjian/oralce_sql_parser/ast/element"
)

type yySymType struct {
	yys      int
	nothing  struct{}
	i        int
	b        bool
	str      string
	node     ast.Node
	anything interface{}
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault            = 57407
	yyEofCode            = 57344
	_add                 = 57350
	_alter               = 57348
	_bfile               = 57377
	_binaryDouble        = 57359
	_binaryFloat         = 57358
	_blob                = 57374
	_by                  = 57400
	_byte                = 57352
	_char                = 57351
	_character           = 57380
	_clob                = 57375
	_collate             = 57393
	_date                = 57362
	_day                 = 57372
	_dec                 = 57386
	_decimal             = 57385
	_double              = 57390
	_doubleQuoteStr      = 57405
	_encrypt             = 57397
	_float               = 57357
	_from                = 57347
	_identified          = 57399
	_int                 = 57388
	_intNumber           = 57403
	_interger            = 57387
	_interval            = 57368
	_invisible           = 57395
	_local               = 57365
	_long                = 57360
	_mouth               = 57371
	_national            = 57383
	_nchar               = 57354
	_nclob               = 57376
	_no                  = 57401
	_nonquotedIdentifier = 57406
	_number              = 57356
	_numeric             = 57384
	_nvarchar2           = 57355
	_precision           = 57391
	_raw                 = 57361
	_real                = 57392
	_rowid               = 57378
	_salt                = 57402
	_second              = 57373
	_select              = 57346
	_singleQuoteStr      = 57404
	_smallInt            = 57389
	_sort                = 57394
	_table               = 57349
	_time                = 57366
	_timestamp           = 57363
	_to                  = 57370
	_urowid              = 57379
	_using               = 57398
	_varchar             = 57382
	_varchar2            = 57353
	_varying             = 57381
	_visible             = 57396
	_with                = 57364
	_year                = 57369
	_zone                = 57367
	yyErrCode            = 57345

	yyMaxDepth = 200
	yyTabOfs   = -120
)

var (
	yyPrec = map[int]int{}

	yyXLAT = map[int]int{
		41:    0,   // ')' (131x)
		44:    1,   // ',' (99x)
		57397: 2,   // _encrypt (80x)
		57395: 3,   // _invisible (76x)
		57396: 4,   // _visible (76x)
		57394: 5,   // _sort (74x)
		57393: 6,   // _collate (70x)
		57403: 7,   // _intNumber (29x)
		40:    8,   // '(' (26x)
		57344: 9,   // $end (22x)
		59:    10,  // ';' (19x)
		57350: 11,  // _add (16x)
		57402: 12,  // _salt (10x)
		57401: 13,  // _no (9x)
		46:    14,  // '.' (8x)
		57404: 15,  // _singleQuoteStr (8x)
		57351: 16,  // _char (7x)
		57405: 17,  // _doubleQuoteStr (6x)
		57406: 18,  // _nonquotedIdentifier (6x)
		57428: 19,  // Identifier (6x)
		42:    20,  // '*' (5x)
		57380: 21,  // _character (5x)
		57361: 22,  // _raw (5x)
		57381: 23,  // _varying (5x)
		57437: 24,  // NumberOrAsterisk (5x)
		57377: 25,  // _bfile (4x)
		57359: 26,  // _binaryDouble (4x)
		57358: 27,  // _binaryFloat (4x)
		57374: 28,  // _blob (4x)
		57375: 29,  // _clob (4x)
		57362: 30,  // _date (4x)
		57386: 31,  // _dec (4x)
		57385: 32,  // _decimal (4x)
		57390: 33,  // _double (4x)
		57357: 34,  // _float (4x)
		57388: 35,  // _int (4x)
		57387: 36,  // _interger (4x)
		57368: 37,  // _interval (4x)
		57360: 38,  // _long (4x)
		57383: 39,  // _national (4x)
		57354: 40,  // _nchar (4x)
		57376: 41,  // _nclob (4x)
		57356: 42,  // _number (4x)
		57384: 43,  // _numeric (4x)
		57355: 44,  // _nvarchar2 (4x)
		57392: 45,  // _real (4x)
		57378: 46,  // _rowid (4x)
		57389: 47,  // _smallInt (4x)
		57363: 48,  // _timestamp (4x)
		57370: 49,  // _to (4x)
		57379: 50,  // _urowid (4x)
		57382: 51,  // _varchar (4x)
		57353: 52,  // _varchar2 (4x)
		57399: 53,  // _identified (3x)
		57352: 54,  // _byte (2x)
		57371: 55,  // _mouth (2x)
		57373: 56,  // _second (2x)
		57366: 57,  // _time (2x)
		57367: 58,  // _zone (2x)
		57408: 59,  // AddColumnClause (2x)
		57411: 60,  // ChangeColumnClause (2x)
		57416: 61,  // ColumnDefinition (2x)
		57418: 62,  // ColumnName (2x)
		57423: 63,  // DropColumnClause (2x)
		57435: 64,  // ModidyColumnClause (2x)
		57440: 65,  // RealColumnDefinition (2x)
		57348: 66,  // _alter (1x)
		57400: 67,  // _by (1x)
		57372: 68,  // _day (1x)
		57365: 69,  // _local (1x)
		57391: 70,  // _precision (1x)
		57349: 71,  // _table (1x)
		57398: 72,  // _using (1x)
		57364: 73,  // _with (1x)
		57369: 74,  // _year (1x)
		57409: 75,  // AlterTableStmt (1x)
		57410: 76,  // AnsiSupportDataTypes (1x)
		57412: 77,  // ChangeColumnClauseList (1x)
		57413: 78,  // CharacterDataTypes (1x)
		57414: 79,  // CollateClause (1x)
		57415: 80,  // ColumnClauses (1x)
		57417: 81,  // ColumnDefinitionList (1x)
		57419: 82,  // ColumnProperties (1x)
		57420: 83,  // Datatype (1x)
		57421: 84,  // DatetimeDataTypes (1x)
		57422: 85,  // DefaultProperties (1x)
		57424: 86,  // EncryptAlgorithm (1x)
		57425: 87,  // EncryptClause (1x)
		57426: 88,  // EncryptionSpec (1x)
		57427: 89,  // IdentifiedByClause (1x)
		57429: 90,  // IntergrityAlgorithm (1x)
		57430: 91,  // InvisibleProperty (1x)
		57431: 92,  // LargeObjectDataTypes (1x)
		57432: 93,  // LongAndRawDataTypes (1x)
		57433: 94,  // MemoptimizeReadClause (1x)
		57434: 95,  // MemoptimizeWriteClause (1x)
		57436: 96,  // NumberDataTypes (1x)
		57438: 97,  // OralceBuiltInDataTypes (1x)
		57439: 98,  // OutOfLinePartStorageList (1x)
		57441: 99,  // RenameColumnClause (1x)
		57442: 100, // RowIdDataTypes (1x)
		57443: 101, // SaltProperty (1x)
		57444: 102, // SortProperty (1x)
		57445: 103, // Start (1x)
		57446: 104, // Statement (1x)
		57447: 105, // TableName (1x)
		57407: 106, // $default (0x)
		57347: 107, // _from (0x)
		57346: 108, // _select (0x)
		57345: 109, // error (0x)
	}

	yySymNames = []string{
		"')'",
		"','",
		"_encrypt",
		"_invisible",
		"_visible",
		"_sort",
		"_collate",
		"_intNumber",
		"'('",
		"$end",
		"';'",
		"_add",
		"_salt",
		"_no",
		"'.'",
		"_singleQuoteStr",
		"_char",
		"_doubleQuoteStr",
		"_nonquotedIdentifier",
		"Identifier",
		"'*'",
		"_character",
		"_raw",
		"_varying",
		"NumberOrAsterisk",
		"_bfile",
		"_binaryDouble",
		"_binaryFloat",
		"_blob",
		"_clob",
		"_date",
		"_dec",
		"_decimal",
		"_double",
		"_float",
		"_int",
		"_interger",
		"_interval",
		"_long",
		"_national",
		"_nchar",
		"_nclob",
		"_number",
		"_numeric",
		"_nvarchar2",
		"_real",
		"_rowid",
		"_smallInt",
		"_timestamp",
		"_to",
		"_urowid",
		"_varchar",
		"_varchar2",
		"_identified",
		"_byte",
		"_mouth",
		"_second",
		"_time",
		"_zone",
		"AddColumnClause",
		"ChangeColumnClause",
		"ColumnDefinition",
		"ColumnName",
		"DropColumnClause",
		"ModidyColumnClause",
		"RealColumnDefinition",
		"_alter",
		"_by",
		"_day",
		"_local",
		"_precision",
		"_table",
		"_using",
		"_with",
		"_year",
		"AlterTableStmt",
		"AnsiSupportDataTypes",
		"ChangeColumnClauseList",
		"CharacterDataTypes",
		"CollateClause",
		"ColumnClauses",
		"ColumnDefinitionList",
		"ColumnProperties",
		"Datatype",
		"DatetimeDataTypes",
		"DefaultProperties",
		"EncryptAlgorithm",
		"EncryptClause",
		"EncryptionSpec",
		"IdentifiedByClause",
		"IntergrityAlgorithm",
		"InvisibleProperty",
		"LargeObjectDataTypes",
		"LongAndRawDataTypes",
		"MemoptimizeReadClause",
		"MemoptimizeWriteClause",
		"NumberDataTypes",
		"OralceBuiltInDataTypes",
		"OutOfLinePartStorageList",
		"RenameColumnClause",
		"RowIdDataTypes",
		"SaltProperty",
		"SortProperty",
		"Start",
		"Statement",
		"TableName",
		"$default",
		"_from",
		"_select",
		"error",
	}

	yyTokenLiteralStrings = map[int]string{
		57403: "int number",
		57404: "single quotes string",
		57405: "double quotes string",
		57406: "nonquoted identifier",
	}

	yyReductions = map[int]struct{ xsym, components int }{
		0:   {0, 1},
		1:   {103, 1},
		2:   {104, 1},
		3:   {104, 2},
		4:   {105, 1},
		5:   {105, 3},
		6:   {19, 1},
		7:   {19, 1},
		8:   {75, 6},
		9:   {94, 0},
		10:  {95, 0},
		11:  {80, 1},
		12:  {80, 1},
		13:  {99, 0},
		14:  {77, 1},
		15:  {77, 2},
		16:  {60, 1},
		17:  {60, 1},
		18:  {60, 1},
		19:  {59, 6},
		20:  {64, 0},
		21:  {63, 0},
		22:  {82, 0},
		23:  {98, 0},
		24:  {81, 1},
		25:  {81, 3},
		26:  {61, 1},
		27:  {65, 7},
		28:  {62, 1},
		29:  {79, 0},
		30:  {79, 2},
		31:  {102, 0},
		32:  {102, 1},
		33:  {91, 0},
		34:  {91, 1},
		35:  {91, 1},
		36:  {85, 0},
		37:  {87, 0},
		38:  {87, 2},
		39:  {88, 4},
		40:  {86, 0},
		41:  {86, 2},
		42:  {89, 0},
		43:  {89, 3},
		44:  {90, 0},
		45:  {90, 1},
		46:  {101, 0},
		47:  {101, 1},
		48:  {101, 2},
		49:  {83, 1},
		50:  {83, 1},
		51:  {24, 1},
		52:  {24, 1},
		53:  {97, 1},
		54:  {97, 1},
		55:  {97, 1},
		56:  {97, 1},
		57:  {97, 1},
		58:  {97, 1},
		59:  {78, 1},
		60:  {78, 4},
		61:  {78, 5},
		62:  {78, 5},
		63:  {78, 4},
		64:  {78, 5},
		65:  {78, 5},
		66:  {78, 1},
		67:  {78, 4},
		68:  {78, 4},
		69:  {96, 1},
		70:  {96, 4},
		71:  {96, 6},
		72:  {96, 1},
		73:  {96, 4},
		74:  {96, 1},
		75:  {96, 1},
		76:  {93, 1},
		77:  {93, 2},
		78:  {93, 4},
		79:  {84, 1},
		80:  {84, 1},
		81:  {84, 4},
		82:  {84, 7},
		83:  {84, 8},
		84:  {84, 4},
		85:  {84, 7},
		86:  {84, 4},
		87:  {84, 7},
		88:  {84, 10},
		89:  {84, 7},
		90:  {92, 1},
		91:  {92, 1},
		92:  {92, 1},
		93:  {92, 1},
		94:  {100, 1},
		95:  {100, 1},
		96:  {100, 4},
		97:  {76, 4},
		98:  {76, 5},
		99:  {76, 5},
		100: {76, 5},
		101: {76, 4},
		102: {76, 5},
		103: {76, 6},
		104: {76, 5},
		105: {76, 6},
		106: {76, 1},
		107: {76, 4},
		108: {76, 6},
		109: {76, 1},
		110: {76, 4},
		111: {76, 6},
		112: {76, 1},
		113: {76, 4},
		114: {76, 6},
		115: {76, 1},
		116: {76, 1},
		117: {76, 1},
		118: {76, 2},
		119: {76, 1},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [221][]uint16{
		// 0
		{66: 124, 75: 123, 103: 121, 122},
		{9: 120},
		{9: 119},
		{9: 118, 340},
		{71: 125},
		// 5
		{17: 128, 127, 126, 105: 129},
		{9: 116, 116, 116, 14: 338},
		{114, 114, 114, 114, 114, 114, 9: 114, 114, 114, 114, 114, 114, 114, 114, 21: 114, 114, 25: 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 50: 114, 114, 114},
		{113, 113, 113, 113, 113, 113, 9: 113, 113, 113, 113, 113, 113, 113, 113, 21: 113, 113, 25: 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 50: 113, 113, 113},
		{9: 111, 111, 111, 94: 130},
		// 10
		{9: 110, 110, 110, 95: 131},
		{9: 107, 107, 139, 59: 136, 135, 63: 138, 137, 77: 133, 80: 132, 99: 134},
		{9: 112, 112},
		{9: 109, 109, 139, 59: 136, 337, 63: 138, 137},
		{9: 108, 108},
		// 15
		{9: 106, 106, 106},
		{9: 104, 104, 104},
		{9: 103, 103, 103},
		{9: 102, 102, 102},
		{8: 140},
		// 20
		{17: 128, 127, 145, 61: 142, 144, 65: 143, 81: 141},
		{332, 333},
		{96, 96},
		{94, 94},
		{16: 155, 21: 174, 164, 25: 171, 162, 161, 168, 169, 165, 179, 178, 183, 160, 181, 180, 167, 163, 176, 157, 170, 159, 177, 158, 184, 172, 182, 166, 50: 173, 175, 156, 76: 148, 78: 149, 83: 146, 152, 92: 153, 151, 96: 150, 147, 100: 154},
		// 25
		{16: 92, 21: 92, 92, 25: 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 50: 92, 92, 92},
		{91, 91, 91, 91, 91, 91, 308, 79: 307},
		{71, 71, 71, 71, 71, 71, 71},
		{70, 70, 70, 70, 70, 70, 70},
		{67, 67, 67, 67, 67, 67, 67},
		// 30
		{66, 66, 66, 66, 66, 66, 66},
		{65, 65, 65, 65, 65, 65, 65},
		{64, 64, 64, 64, 64, 64, 64},
		{63, 63, 63, 63, 63, 63, 63},
		{62, 62, 62, 62, 62, 62, 62},
		// 35
		{61, 61, 61, 61, 61, 61, 61, 8: 296, 23: 297},
		{8: 289},
		{54, 54, 54, 54, 54, 54, 54, 8: 282, 23: 283},
		{8: 279},
		{51, 51, 51, 51, 51, 51, 51, 8: 273},
		// 40
		{48, 48, 48, 48, 48, 48, 48, 8: 270},
		{46, 46, 46, 46, 46, 46, 46},
		{45, 45, 45, 45, 45, 45, 45},
		{44, 44, 44, 44, 44, 44, 44, 22: 269},
		{8: 266},
		// 45
		{41, 41, 41, 41, 41, 41, 41},
		{40, 40, 40, 40, 40, 40, 40, 8: 257},
		{68: 236, 74: 235},
		{30, 30, 30, 30, 30, 30, 30},
		{29, 29, 29, 29, 29, 29, 29},
		// 50
		{28, 28, 28, 28, 28, 28, 28},
		{27, 27, 27, 27, 27, 27, 27},
		{26, 26, 26, 26, 26, 26, 26},
		{25, 25, 25, 25, 25, 25, 25, 8: 232},
		{8: 225, 23: 226},
		// 55
		{8: 222},
		{16: 207, 21: 206},
		{14, 14, 14, 14, 14, 14, 14, 8: 200},
		{11, 11, 11, 11, 11, 11, 11, 8: 194},
		{8, 8, 8, 8, 8, 8, 8, 8: 186},
		// 60
		{5, 5, 5, 5, 5, 5, 5},
		{4, 4, 4, 4, 4, 4, 4},
		{3, 3, 3, 3, 3, 3, 3},
		{70: 185},
		{1, 1, 1, 1, 1, 1, 1},
		// 65
		{2, 2, 2, 2, 2, 2, 2},
		{7: 187, 20: 188, 24: 189},
		{69, 69, 14: 69},
		{68, 68, 14: 68},
		{190, 14: 191},
		// 70
		{7, 7, 7, 7, 7, 7, 7},
		{7: 192},
		{193},
		{6, 6, 6, 6, 6, 6, 6},
		{7: 187, 20: 188, 24: 195},
		// 75
		{196, 14: 197},
		{10, 10, 10, 10, 10, 10, 10},
		{7: 198},
		{199},
		{9, 9, 9, 9, 9, 9, 9},
		// 80
		{7: 187, 20: 188, 24: 201},
		{202, 14: 203},
		{13, 13, 13, 13, 13, 13, 13},
		{7: 204},
		{205},
		// 85
		{12, 12, 12, 12, 12, 12, 12},
		{8: 215, 23: 216},
		{8: 208, 23: 209},
		{7: 213},
		{8: 210},
		// 90
		{7: 211},
		{212},
		{15, 15, 15, 15, 15, 15, 15},
		{214},
		{16, 16, 16, 16, 16, 16, 16},
		// 95
		{7: 220},
		{8: 217},
		{7: 218},
		{219},
		{17, 17, 17, 17, 17, 17, 17},
		// 100
		{221},
		{18, 18, 18, 18, 18, 18, 18},
		{7: 223},
		{224},
		{19, 19, 19, 19, 19, 19, 19},
		// 105
		{7: 230},
		{8: 227},
		{7: 228},
		{229},
		{22, 22, 22, 22, 22, 22, 22},
		// 110
		{231},
		{23, 23, 23, 23, 23, 23, 23},
		{7: 233},
		{234},
		{24, 24, 24, 24, 24, 24, 24},
		// 115
		{8: 251, 49: 250},
		{8: 238, 49: 237},
		{56: 246},
		{7: 239},
		{240},
		// 120
		{49: 241},
		{56: 242},
		{33, 33, 33, 33, 33, 33, 33, 8: 243},
		{7: 244},
		{245},
		// 125
		{32, 32, 32, 32, 32, 32, 32},
		{34, 34, 34, 34, 34, 34, 34, 8: 247},
		{7: 248},
		{249},
		{31, 31, 31, 31, 31, 31, 31},
		// 130
		{55: 256},
		{7: 252},
		{253},
		{49: 254},
		{55: 255},
		// 135
		{35, 35, 35, 35, 35, 35, 35},
		{36, 36, 36, 36, 36, 36, 36},
		{7: 258},
		{259},
		{39, 39, 39, 39, 39, 39, 39, 73: 260},
		// 140
		{57: 261, 69: 262},
		{58: 265},
		{57: 263},
		{58: 264},
		{37, 37, 37, 37, 37, 37, 37},
		// 145
		{38, 38, 38, 38, 38, 38, 38},
		{7: 267},
		{268},
		{42, 42, 42, 42, 42, 42, 42},
		{43, 43, 43, 43, 43, 43, 43},
		// 150
		{7: 187, 20: 188, 24: 271},
		{272},
		{47, 47, 47, 47, 47, 47, 47},
		{7: 187, 20: 188, 24: 274},
		{275, 276},
		// 155
		{50, 50, 50, 50, 50, 50, 50},
		{7: 277},
		{278},
		{49, 49, 49, 49, 49, 49, 49},
		{7: 280},
		// 160
		{281},
		{52, 52, 52, 52, 52, 52, 52},
		{7: 287},
		{8: 284},
		{7: 285},
		// 165
		{286},
		{20, 20, 20, 20, 20, 20, 20},
		{288},
		{53, 53, 53, 53, 53, 53, 53},
		{7: 290},
		// 170
		{291, 16: 293, 54: 292},
		{57, 57, 57, 57, 57, 57, 57},
		{295},
		{294},
		{55, 55, 55, 55, 55, 55, 55},
		// 175
		{56, 56, 56, 56, 56, 56, 56},
		{7: 301},
		{8: 298},
		{7: 299},
		{300},
		// 180
		{21, 21, 21, 21, 21, 21, 21},
		{302, 16: 304, 54: 303},
		{60, 60, 60, 60, 60, 60, 60},
		{306},
		{305},
		// 185
		{58, 58, 58, 58, 58, 58, 58},
		{59, 59, 59, 59, 59, 59, 59},
		{89, 89, 89, 89, 89, 311, 102: 310},
		{17: 128, 127, 309},
		{90, 90, 90, 90, 90, 90},
		// 190
		{87, 87, 87, 313, 314, 91: 312},
		{88, 88, 88, 88, 88},
		{84, 84, 84, 85: 315},
		{86, 86, 86},
		{85, 85, 85},
		// 195
		{83, 83, 317, 87: 316},
		{93, 93},
		{80, 80, 12: 80, 80, 15: 80, 53: 80, 72: 320, 86: 319, 88: 318},
		{82, 82},
		{78, 78, 12: 78, 78, 15: 78, 53: 323, 89: 322},
		// 200
		{15: 321},
		{79, 79, 12: 79, 79, 15: 79, 53: 79},
		{76, 76, 12: 76, 76, 15: 327, 90: 326},
		{67: 324},
		{17: 128, 127, 325},
		// 205
		{77, 77, 12: 77, 77, 15: 77},
		{74, 74, 12: 329, 330, 101: 328},
		{75, 75, 12: 75, 75},
		{81, 81},
		{73, 73},
		// 210
		{12: 331},
		{72, 72},
		{9: 98, 98, 98, 82: 335},
		{17: 128, 127, 145, 61: 334, 144, 65: 143},
		{95, 95},
		// 215
		{9: 97, 97, 97, 98: 336},
		{9: 101, 101, 101},
		{9: 105, 105, 105},
		{17: 128, 127, 339},
		{9: 115, 115, 115},
		// 220
		{9: 117},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 109

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			yylex.(*yyLexImpl).result = yyS[yypt-0].node
		}
	case 2:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 3:
		{
			yyVAL.node = yyS[yypt-1].node
		}
	case 4:
		{
			yyVAL.anything = &ast.TableName{
				Table: yyS[yypt-0].anything.(*element.Identifier),
			}
		}
	case 5:
		{
			yyVAL.anything = &ast.TableName{
				Schema: yyS[yypt-2].anything.(*element.Identifier),
				Table:  yyS[yypt-0].anything.(*element.Identifier),
			}
		}
	case 6:
		{
			yyVAL.anything = &element.Identifier{
				Typ:   element.IdentifierTypeNonQuoted,
				Value: yyS[yypt-0].str,
			}
		}
	case 7:
		{
			yyVAL.anything = &element.Identifier{
				Typ:   element.IdentifierTypeQuoted,
				Value: yyS[yypt-0].str,
			}
		}
	case 8:
		{
			yyVAL.node = &ast.AlterTableStmt{
				TableName:     yyS[yypt-3].anything.(*ast.TableName),
				ColumnClauses: yyS[yypt-0].anything.([]ast.ColumnClause),
			}
		}
	case 9:
		{
			// TODO
		}
	case 10:
		{
			// TODO
		}
	case 11:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 12:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 13:
		{
			// todo:
		}
	case 14:
		{
			yyVAL.anything = []ast.ColumnClause{yyS[yypt-0].anything.(ast.ColumnClause)}
		}
	case 15:
		{
			yyVAL.anything = append(yyS[yypt-1].anything.([]ast.ColumnClause), yyS[yypt-0].anything.(ast.ColumnClause))
		}
	case 16:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 17:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 18:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 19:
		{
			yyVAL.anything = &ast.AddColumnClause{
				Columns: yyS[yypt-3].anything.([]*ast.ColumnDefine),
			}
		}
	case 20:
		{
			// todo:
		}
	case 21:
		{
			// todo:
		}
	case 22:
		{
			// TODO
		}
	case 23:
		{
			// TODO
		}
	case 24:
		{
			yyVAL.anything = []*ast.ColumnDefine{yyS[yypt-0].anything.(*ast.ColumnDefine)}
		}
	case 25:
		{
			yyVAL.anything = append(yyS[yypt-2].anything.([]*ast.ColumnDefine), yyS[yypt-0].anything.(*ast.ColumnDefine))
		}
	case 26:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 27:
		{
			var collation *ast.Collation
			if yyS[yypt-4].anything != nil {
				collation = yyS[yypt-4].anything.(*ast.Collation)
			}
			var invisible *ast.InvisibleProperty
			if yyS[yypt-2].anything != nil {
				invisible = yyS[yypt-2].anything.(*ast.InvisibleProperty)
			}

			yyVAL.anything = &ast.ColumnDefine{
				ColumnName:        yyS[yypt-6].anything.(*element.Identifier),
				Datatype:          yyS[yypt-5].anything.(element.Datatype),
				Collation:         collation,
				Sort:              ast.SortProperty(yyS[yypt-3].b),
				InvisibleProperty: invisible,
			}
		}
	case 28:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 29:
		{
			yyVAL.anything = nil
		}
	case 30:
		{
			yyVAL.anything = &ast.Collation{Name: yyS[yypt-0].anything.(*element.Identifier)}
		}
	case 31:
		{
			yyVAL.b = false
		}
	case 32:
		{
			yyVAL.b = true
		}
	case 33:
		{
			yyVAL.anything = nil
		}
	case 34:
		{
			yyVAL.anything = &ast.InvisibleProperty{Type: ast.InvisiblePropertyInvisible}
		}
	case 35:
		{
			yyVAL.anything = &ast.InvisibleProperty{Type: ast.InvisiblePropertyVisible}
		}
	case 37:
		{
			// empty
		}
	case 40:
		{
			// empty
		}
	case 42:
		{
			// empty
		}
	case 44:
		{
			// empty
		}
	case 46:
		{
			// empty
		}
	case 49:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 50:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 51:
		{
			yyVAL.anything = &element.NumberOrAsterisk{Number: yyS[yypt-0].i}
		}
	case 52:
		{
			yyVAL.anything = &element.NumberOrAsterisk{IsAsterisk: true}
		}
	case 53:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 54:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 55:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 56:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 57:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 58:
		{
			yyVAL.anything = yyS[yypt-0].anything
		}
	case 59:
		{
			d := &element.Char{}
			d.SetDataDefine(element.DataDefineChar)
			yyVAL.anything = d
		}
	case 60:
		{
			size := yyS[yypt-1].i
			d := &element.Char{Size: &size}
			d.SetDataDefine(element.DataDefineChar)
			yyVAL.anything = d
		}
	case 61:
		{
			size := yyS[yypt-2].i
			d := &element.Char{Size: &size, IsByteSize: true}
			d.SetDataDefine(element.DataDefineChar)
			yyVAL.anything = d
		}
	case 62:
		{
			size := yyS[yypt-2].i
			d := &element.Char{Size: &size, IsCharSize: true}
			d.SetDataDefine(element.DataDefineChar)
			d.SetDataDefine(element.DataDefineChar)
			yyVAL.anything = d
		}
	case 63:
		{
			size := yyS[yypt-1].i
			d := &element.Varchar2{}
			d.Size = &size
			d.SetDataDefine(element.DataDefineVarchar2)
			yyVAL.anything = d
		}
	case 64:
		{
			size := yyS[yypt-2].i
			d := &element.Varchar2{}
			d.Size = &size
			d.IsByteSize = true
			d.SetDataDefine(element.DataDefineVarchar2)
			yyVAL.anything = d
		}
	case 65:
		{
			size := yyS[yypt-2].i
			d := &element.Varchar2{}
			d.Size = &size
			d.IsCharSize = true
			d.SetDataDefine(element.DataDefineVarchar2)
			yyVAL.anything = d
		}
	case 66:
		{
			d := &element.NChar{}
			d.SetDataDefine(element.DataDefineNChar)
			yyVAL.anything = d
		}
	case 67:
		{
			size := yyS[yypt-1].i
			d := &element.NChar{Size: &size}
			d.SetDataDefine(element.DataDefineNChar)
			yyVAL.anything = d
		}
	case 68:
		{
			size := yyS[yypt-1].i
			d := &element.NVarchar2{}
			d.Size = &size
			d.SetDataDefine(element.DataDefineNVarChar2)
			yyVAL.anything = d
		}
	case 69:
		{
			d := &element.Number{}
			d.SetDataDefine(element.DataDefineNumber)
			yyVAL.anything = d
		}
	case 70:
		{
			precision := yyS[yypt-1].anything.(*element.NumberOrAsterisk)
			d := &element.Number{Precision: precision}
			d.SetDataDefine(element.DataDefineNumber)
			yyVAL.anything = d
		}
	case 71:
		{
			precision := yyS[yypt-3].anything.(*element.NumberOrAsterisk)
			scale := yyS[yypt-1].i
			d := &element.Number{Precision: precision, Scale: &scale}
			d.SetDataDefine(element.DataDefineNumber)
			yyVAL.anything = d
		}
	case 72:
		{
			d := &element.Float{}
			d.SetDataDefine(element.DataDefineFloat)
			yyVAL.anything = d
		}
	case 73:
		{
			precision := yyS[yypt-1].anything.(*element.NumberOrAsterisk)
			d := &element.Float{Precision: precision}
			d.SetDataDefine(element.DataDefineFloat)
			yyVAL.anything = d
		}
	case 74:
		{
			d := &element.BinaryFloat{}
			d.SetDataDefine(element.DataDefineBinaryFloat)
			yyVAL.anything = d
		}
	case 75:
		{
			d := &element.BinaryDouble{}
			d.SetDataDefine(element.DataDefineBinaryDouble)
			yyVAL.anything = d
		}
	case 76:
		{
			d := &element.Long{}
			d.SetDataDefine(element.DataDefineLong)
			yyVAL.anything = d
		}
	case 77:
		{
			d := &element.LongRaw{}
			d.SetDataDefine(element.DataDefineLongRaw)
			yyVAL.anything = d
		}
	case 78:
		{
			size := yyS[yypt-1].i
			d := &element.Raw{Size: &size}
			d.SetDataDefine(element.DataDefineRaw)
			yyVAL.anything = d
		}
	case 79:
		{
			d := &element.Date{}
			d.SetDataDefine(element.DataDefineDate)
			yyVAL.anything = d
		}
	case 80:
		{
			d := &element.Timestamp{}
			d.SetDataDefine(element.DataDefineTimestamp)
			yyVAL.anything = d
		}
	case 81:
		{
			precision := yyS[yypt-1].i
			d := &element.Timestamp{FractionalSecondsPrecision: &precision}
			d.SetDataDefine(element.DataDefineTimestamp)
			yyVAL.anything = d
		}
	case 82:
		{
			precision := yyS[yypt-4].i
			d := &element.Timestamp{FractionalSecondsPrecision: &precision, WithTimeZone: true}
			d.SetDataDefine(element.DataDefineTimestamp)
			yyVAL.anything = d
		}
	case 83:
		{
			precision := yyS[yypt-5].i
			d := &element.Timestamp{FractionalSecondsPrecision: &precision, WithLocalTimeZone: true}
			d.SetDataDefine(element.DataDefineTimestamp)
			yyVAL.anything = d
		}
	case 84:
		{
			d := &element.IntervalYear{}
			d.SetDataDefine(element.DataDefineIntervalYear)
			yyVAL.anything = d
		}
	case 85:
		{
			precision := yyS[yypt-3].i
			d := &element.IntervalYear{Precision: &precision}
			d.SetDataDefine(element.DataDefineIntervalYear)
			yyVAL.anything = d
		}
	case 86:
		{
			d := &element.IntervalDay{}
			d.SetDataDefine(element.DataDefineIntervalDay)
			yyVAL.anything = d
		}
	case 87:
		{
			precision := yyS[yypt-3].i
			d := &element.IntervalDay{Precision: &precision}
			d.SetDataDefine(element.DataDefineIntervalDay)
			yyVAL.anything = d
		}
	case 88:
		{
			precision := yyS[yypt-6].i
			sPrecision := yyS[yypt-1].i
			d := &element.IntervalDay{Precision: &precision, FractionalSecondsPrecision: &sPrecision}
			d.SetDataDefine(element.DataDefineIntervalDay)
			yyVAL.anything = d
		}
	case 89:
		{
			sPrecision := yyS[yypt-1].i
			d := &element.IntervalDay{FractionalSecondsPrecision: &sPrecision}
			d.SetDataDefine(element.DataDefineIntervalDay)
			yyVAL.anything = d
		}
	case 90:
		{
			d := &element.Blob{}
			d.SetDataDefine(element.DataDefineBlob)
			yyVAL.anything = d
		}
	case 91:
		{
			d := &element.Clob{}
			d.SetDataDefine(element.DataDefineClob)
			yyVAL.anything = d
		}
	case 92:
		{
			d := &element.NClob{}
			d.SetDataDefine(element.DataDefineNClob)
			yyVAL.anything = d
		}
	case 93:
		{
			d := &element.BFile{}
			d.SetDataDefine(element.DataDefineBFile)
			yyVAL.anything = d
		}
	case 94:
		{
			d := &element.RowId{}
			d.SetDataDefine(element.DataDefineRowId)
			yyVAL.anything = d
		}
	case 95:
		{
			d := &element.URowId{}
			d.SetDataDefine(element.DataDefineURowId)
			yyVAL.anything = d
		}
	case 96:
		{
			size := yyS[yypt-1].i
			d := &element.URowId{Size: &size}
			d.SetDataDefine(element.DataDefineURowId)
			yyVAL.anything = d
		}
	case 97:
		{
			d := &element.Char{}
			d.SetDataDefine(element.DataDefineCharacter)
			yyVAL.anything = d
		}
	case 98:
		{
			size := yyS[yypt-1].i
			d := &element.Varchar2{}
			d.Size = &size
			d.SetDataDefine(element.DataDefineCharacterVarying)
			yyVAL.anything = d
		}
	case 99:
		{
			size := yyS[yypt-1].i
			d := &element.Varchar2{}
			d.Size = &size
			d.SetDataDefine(element.DataDefineCharVarying)
			yyVAL.anything = d
		}
	case 100:
		{
			size := yyS[yypt-1].i
			d := &element.NVarchar2{}
			d.Size = &size
			d.SetDataDefine(element.DataDefineNCharVarying)
			yyVAL.anything = d
		}
	case 101:
		{
			size := yyS[yypt-1].i
			d := &element.Varchar2{}
			d.Size = &size
			d.SetDataDefine(element.DataDefineVarchar)
			yyVAL.anything = d
		}
	case 102:
		{
			size := yyS[yypt-1].i
			d := &element.NChar{Size: &size}
			d.SetDataDefine(element.DataDefineNationalCharacter)
			yyVAL.anything = d
		}
	case 103:
		{
			size := yyS[yypt-1].i
			d := &element.NVarchar2{}
			d.Size = &size
			d.SetDataDefine(element.DataDefineNationalCharacterVarying)
			yyVAL.anything = d
		}
	case 104:
		{
			size := yyS[yypt-1].i
			d := &element.NChar{Size: &size}
			d.SetDataDefine(element.DataDefineNationalChar)
			yyVAL.anything = d
		}
	case 105:
		{
			size := yyS[yypt-1].i
			d := &element.NVarchar2{}
			d.Size = &size
			d.SetDataDefine(element.DataDefineNationalCharVarying)
			yyVAL.anything = d
		}
	case 106:
		{
			d := &element.Number{}
			d.SetDataDefine(element.DataDefineNumeric)
			yyVAL.anything = d
		}
	case 107:
		{
			precision := yyS[yypt-1].anything.(*element.NumberOrAsterisk)
			d := &element.Number{Precision: precision}
			d.SetDataDefine(element.DataDefineNumeric)
			yyVAL.anything = d
		}
	case 108:
		{
			precision := yyS[yypt-3].anything.(*element.NumberOrAsterisk)
			scale := yyS[yypt-1].i
			d := &element.Number{Precision: precision, Scale: &scale}
			d.SetDataDefine(element.DataDefineNumeric)
			yyVAL.anything = d
		}
	case 109:
		{
			d := &element.Number{}
			d.SetDataDefine(element.DataDefineDecimal)
			yyVAL.anything = d
		}
	case 110:
		{
			precision := yyS[yypt-1].anything.(*element.NumberOrAsterisk)
			d := &element.Number{Precision: precision}
			d.SetDataDefine(element.DataDefineDecimal)
			yyVAL.anything = d
		}
	case 111:
		{
			precision := yyS[yypt-3].anything.(*element.NumberOrAsterisk)
			scale := yyS[yypt-1].i
			d := &element.Number{Precision: precision, Scale: &scale}
			d.SetDataDefine(element.DataDefineDecimal)
			yyVAL.anything = d
		}
	case 112:
		{
			d := &element.Number{}
			d.SetDataDefine(element.DataDefineDec)
			yyVAL.anything = d
		}
	case 113:
		{
			precision := yyS[yypt-1].anything.(*element.NumberOrAsterisk)
			d := &element.Number{Precision: precision}
			d.SetDataDefine(element.DataDefineDec)
			yyVAL.anything = d
		}
	case 114:
		{
			precision := yyS[yypt-3].anything.(*element.NumberOrAsterisk)
			scale := yyS[yypt-1].i
			d := &element.Number{Precision: precision, Scale: &scale}
			d.SetDataDefine(element.DataDefineDec)
			yyVAL.anything = d
		}
	case 115:
		{
			precision := &element.NumberOrAsterisk{Number: 38}
			d := &element.Number{Precision: precision}
			d.SetDataDefine(element.DataDefineInteger)
			yyVAL.anything = d
		}
	case 116:
		{
			precision := &element.NumberOrAsterisk{Number: 38}
			d := &element.Number{Precision: precision}
			d.SetDataDefine(element.DataDefineInt)
			yyVAL.anything = d
		}
	case 117:
		{
			precision := &element.NumberOrAsterisk{Number: 38}
			d := &element.Number{Precision: precision}
			d.SetDataDefine(element.DataDefineSmallInt)
			yyVAL.anything = d
		}
	case 118:
		{
			precision := &element.NumberOrAsterisk{Number: 126}
			d := &element.Float{Precision: precision}
			d.SetDataDefine(element.DataDefineDoublePrecision)
			yyVAL.anything = d
		}
	case 119:
		{
			precision := &element.NumberOrAsterisk{Number: 63}
			d := &element.Float{Precision: precision}
			d.SetDataDefine(element.DataDefineReal)
			yyVAL.anything = d
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
